version: '2'
services:
  web:
    build:
      context: .
      dockerfile: local.Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "4200:4200"
    command: bash -c "npm install && npm run start:docker"
