version: '2'
services:
  web:
    image: 090999229429.dkr.ecr.${AWS_REGION}.amazonaws.com/${IMAGE_REPO}:${IMAGE_LABEL}
    ports:
      - "3000:3000"
    # npm run start:docker just runs this anyway: (after "npm run standardize")
    # command: bash -c "ng serve --host 0.0.0.0 --port 3000"
    command: ["/usr/src/app/configure-and-run"]
    # changed the port from 4200 to 3000 for production
    # TODO: maybe change command to be ["ng", "serve", ...] ?
    environment:
      # ecs-cli compose substitutes these in, from .env in this directory:
      TIMESTAMP: ${TIMESTAMP}
      WEB_DOMAIN: ${WEB_DOMAIN}
